sudo: required

matrix:
    include:
        - os: linux
          dist: trusty
          language: python
          python: 2.7
        - os: osx
          language: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                    ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3           ; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./test/dependencies_osx.sh     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/dependencies_linux.sh ; fi
    - sudo ./test/tests.sh -o $TRAVIS_OS_NAME

after_success:
    - bash <(curl -s https://codecov.io/bash)
